### ISSUE TITLE
[BUG] Import terrain gltf in blender 3.5

### ISSUE THREAD

**Issue by docstrang** [turanszkij/WickedEngine#701]
When importing a terrain (gltf) in blender 3.5 it gives me the following error.

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\__init__.py", line 1272, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\__init__.py", line 1300, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\__init__.py", line 1320, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 37, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 44, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 36, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 30, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 223, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 27, in create
    return create_mesh(gltf, mesh_idx, skin_idx)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 48, in create_mesh
    do_primitives(gltf, mesh_idx, skin_idx, mesh, tmp_ob)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 392, in do_primitives
    BlenderMaterial.create(gltf, prim.material, vertex_color)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_material.py", line 49, in create
    pbr_metallic_roughness(mh)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_pbrMetallicRoughness.py", line 161, in pbr_metallic_roughness
    specular(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_KHR_materials_specular.py", line 218, in specular
    f0_from_ior = ((ior - 1)/(ior + 1))**2
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

**Comment by turanszkij** [comment]
I'm using Blender 3.2 and it works with that version. Not sure what I can do if some other version is having problem with it, but I'll see.
